package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorEspacios;
import ec.ups.edu.controlador.ControladorParqueadero;
import ec.ups.edu.controlador.ControladorVehiculo;
import images.ControladorImagenes;
import ec.ups.edu.modelo.Parqueadero;
import ec.ups.edu.modelo.Vehiculo;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

//librerias itextPDF
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.ImageIcon;


/**
 *
 * @author santi
 */
public class VentanaParqueadero extends javax.swing.JInternalFrame {

    Vehiculo vehiculo;
    Parqueadero parqueadero;
    ControladorVehiculo controladorVehiculo;
    ControladorParqueadero controladorParqueadero;
    //ControladorFabVehiculos controladorFacVehiculos;
    ControladorImagenes controladorImagenes;
    ControladorEspacios controladorEspacios;
    Parqueadero parqueaderoActualizar;
    int cont;

    public VentanaParqueadero(Vehiculo vehiculo, ControladorVehiculo controladorVehiculo, Parqueadero parqueadero,
            ControladorParqueadero controladorParqueadero, 
            ControladorImagenes controladorImagenes) {

        initComponents();

        this.vehiculo = vehiculo;
        this.controladorVehiculo = controladorVehiculo;
        this.parqueadero = parqueadero;
        this.controladorParqueadero = controladorParqueadero;
        agregarDatosCbx(cbxVehiculo);
        this.parqueadero = parqueadero;
        this.controladorImagenes = controladorImagenes;

        verParqueadero();
        cont = 1;

//ingresarPanel();
//agregarPane();
    }

    private void agregarDatosCbx(JComboBox cbxVehiculo) {

        controladorVehiculo.llenarComboBox(cbxVehiculo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chooserFechaSalida = new rojeru_san.componentes.RSDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cbxVehiculo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtEspacio = new javax.swing.JTextField();
        btnIngresarAuto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        btnRetirarVehiculo = new javax.swing.JButton();
        cbxTipoArrendamiento = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscarEspacio = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Fecha Ingreso");

        jLabel2.setText("Fecha Salida");

        jLabel3.setText("Seleccione una placa");

        jLabel5.setText("Escoja el espacio");

        btnIngresarAuto.setText("Ingresar auto");
        btnIngresarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarAutoActionPerformed(evt);
            }
        });

        jLabel7.setText("VENTANA PARQUEADERO");

        btnRetirarVehiculo.setText("Retirar Vehiculo");
        btnRetirarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarVehiculoActionPerformed(evt);
            }
        });

        cbxTipoArrendamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Contrato", "Normal" }));

        jLabel8.setText("Tipo de arrendamiento");

        panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooserFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(cbxVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEspacio)
                    .addComponent(txtFechaIngreso)
                    .addComponent(cbxTipoArrendamiento, 0, 234, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)))
                .addContainerGap(738, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetirarVehiculo)
                            .addComponent(btnIngresarAuto)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBuscarEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(295, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooserFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxTipoArrendamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnIngresarAuto)
                .addGap(18, 18, 18)
                .addComponent(btnRetirarVehiculo)
                .addGap(86, 86, 86))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(11, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int filas = 5;
    int columnas = 10;
    JLabel label1;
    int ejex = 130;
    int ejey = 20;

    public void ingresarPanel() {

        int filas = 5;
        int columnas = 10;
        int cont = 1;

        JLabel label[][] = new JLabel[filas][columnas];

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {

                label[i][j] = new JLabel();
                label[i][j].setBounds(ejex, ejey, 40, 40);
                label[i][j].setText(" " + cont++ + " ");
                label[i][j].setBorder(BorderFactory.createLineBorder(Color.BLACK));

                panel.add(label[i][j]);

                ejex += 45;

            }

            ejex = 130;
            ejey += 100;

        }

    }

    public void verParqueadero() {

        panel.updateUI();

        int filas = 5;
        int columnas = 10;
        int cont = 1;

        List<Parqueadero> listaP = controladorParqueadero.findAll();
        JLabel label[][] = new JLabel[filas][columnas];

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {

                Parqueadero parq = null;

                for (Parqueadero parqueadero1 : listaP) {

                    if (cont == parqueadero1.getPuesto()) {

                        if (!parqueadero1.getTipo().equals("retirado")) {

                            parq = parqueadero1;

                        }

                    }

                }

                if (parq == null) {

                    label[i][j] = new JLabel();
                    label[i][j].setBounds(ejex, ejey, 40, 40);
                    label[i][j].setText(" " + cont++ + " ");
                    label[i][j].setBorder(BorderFactory.createLineBorder(Color.BLACK));

                    panel.add(label[i][j]);
                } else {

                    label[i][j] = new JLabel();
                    label[i][j].setBounds(ejex, ejey, 40, 40);
                    label[i][j].setText(" " + cont++ + " ");
                    label[i][j].setBorder(BorderFactory.createLineBorder(Color.BLACK));

                    if (parq.getTipo().equals("ingreso")) {

                        label[i][j].setIcon(new ImageIcon(getClass().getResource("carro-deportivo.png")));

                    } else if (parq.getTipo().equals("ingreso")) {

                        label[i][j].setIcon(new ImageIcon(getClass().getResource("carro-deportivo.png")));

                    }

                }

                panel.add(label[i][j]);

                ejex += 45;

            }

            ejex = 130;
            ejey += 100;

        }

        panel.updateUI();
    }

    private void btnIngresarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarAutoActionPerformed

        String fechaIngreso = txtFechaIngreso.getText();
        String placa = cbxVehiculo.getSelectedItem().toString();
        int espacio = Integer.parseInt(txtEspacio.getText());
        String tipoArrendamiento = cbxTipoArrendamiento.getSelectedItem().toString();
        Date fechaSalida = chooserFechaSalida.getDatoFecha();

        txtFechaIngreso.setText(new Date() + "");

        if (placa.isEmpty() || String.valueOf(espacio).isEmpty()
                || tipoArrendamiento.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Llene los campos");

        } else {

            List<Parqueadero> lista = vehiculo.getLista();
            lista.add(new Parqueadero(espacio, "ingreso", new Date(), null, 0, vehiculo));
            vehiculo.setLista(lista);
            controladorEspacios = new ControladorEspacios(panel, espacio, "ingreso");
            verParqueadero();

            try {
                controladorVehiculo.update(vehiculo);
            } catch (Exception ex) {
                Logger.getLogger(VentanaParqueadero.class.getName()).log(Level.SEVERE, null, ex);

            }

            Document document = new Document();

            try {

                PdfWriter.getInstance(document, new FileOutputStream("ingreso" + cont++ + ".pdf"));
                document.open();
                document.add(new Paragraph("FACTURA EMOV-EC"));
                document.add(new Paragraph("----------------------------------------------"));
                document.add(new Paragraph("Espacio Estacionamiento: " + espacio));
                document.add(new Paragraph("Placa Vehiculo: " + placa));
                document.add(new Paragraph("Fecha Ingreso: " + fechaIngreso));
                document.add(new Paragraph("Tipo arrendamiento: " + tipoArrendamiento));

            } catch (DocumentException e) {
                e.printStackTrace();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } finally {

                document.close();

            }


            /*            contratos.setPuesto(espacio);
            contratos.setFechaIngreso(new Date());
            contratos.setFechaSalida(fechaSalida);
             */
        }

    }//GEN-LAST:event_btnIngresarAutoActionPerformed

    public double dineroApagar(Date fechaIngeso, Date fechaSalida) {

        int anioIngreso = fechaIngeso.getYear() * 525600;
        int mesIngreso = fechaIngeso.getMonth() * 43800;
        int diaIngreso = fechaIngeso.getDay() * 1440;
        int horaIngreso = fechaIngeso.getHours() * 60;
        int minutoIngreso = fechaIngeso.getMinutes();

        int anioSalida = fechaSalida.getYear() * 525600;
        int mesSalida = fechaSalida.getMonth() * 43800;
        int diaSalida = fechaSalida.getDay() * 1440;
        int horaSalida = fechaIngeso.getHours() * 60;
        int minutoSalida = fechaIngeso.getMinutes();

        int ingreso = anioIngreso + mesIngreso + diaIngreso + horaIngreso + minutoIngreso;
        int salida = anioIngreso + mesSalida + diaSalida + horaSalida + minutoSalida;

        int total = ingreso - salida;
        int fracciones = (int) total / 10;

        fracciones++;

        double dineroCob = fracciones * 0.30;

        return Math.abs(dineroCob);

    }


    private void btnRetirarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarVehiculoActionPerformed

        String fechaIngreso = txtFechaIngreso.getText();
        String placa = cbxVehiculo.getSelectedItem().toString();
        int espacio = Integer.parseInt(txtEspacio.getText());
        String tipoArrendamiento = cbxTipoArrendamiento.getSelectedItem().toString();

        Date fechaSalida = chooserFechaSalida.getDatoFecha();

        parqueaderoActualizar.setTotal(dineroApagar(parqueaderoActualizar.getIngreso(), fechaSalida));
        parqueaderoActualizar.setSalida(fechaSalida);
        parqueaderoActualizar.setTipo("retirado");

        JOptionPane.showMessageDialog(this, dineroApagar(parqueaderoActualizar.getIngreso(), fechaSalida));

        try {
            controladorParqueadero.update(parqueaderoActualizar);
        } catch (Exception ex) {
            Logger.getLogger(VentanaParqueadero.class.getName()).log(Level.SEVERE, null, ex);
        }
        controladorEspacios = new ControladorEspacios(panel, parqueaderoActualizar.getPuesto(), "retirado");

        Document document = new Document();

        try {

            PdfWriter.getInstance(document, new FileOutputStream("retirar" + cont++ + ".pdf"));
            document.open();
            document.add(new Paragraph("FACTURA EMOV-EC"));
            document.add(new Paragraph("----------------------------------------------"));
            document.add(new Paragraph("Espacio Estacionamiento: " + espacio));
            document.add(new Paragraph("Placa Vehiculo: " + placa));
            document.add(new Paragraph("Fecha Ingreso: " + fechaIngreso));
            document.add(new Paragraph("Fecha Salida: " + fechaSalida));
            document.add(new Paragraph("Total: " + dineroApagar(parqueaderoActualizar.getIngreso(), fechaSalida)));
            

        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } finally {

            document.close();

        }


    }//GEN-LAST:event_btnRetirarVehiculoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        List<Parqueadero> lista = controladorParqueadero.findAll();

        int espacio = Integer.parseInt(txtBuscarEspacio.getText());

        if (lista.isEmpty()) {

            JOptionPane.showMessageDialog(this, "No existen datos en la lista ");

        } else {

            for (Parqueadero parqueadero1 : lista) {

                if (parqueadero1.getPuesto() == espacio && !parqueadero1.getTipo().equals("retirado")) {

                    parqueaderoActualizar = parqueadero1;

                    txtEspacio.setText(parqueaderoActualizar.getPuesto() + "");
                    txtFechaIngreso.setText(parqueaderoActualizar.getIngreso() + "");

                }

            }

        }


    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnIngresarAuto;
    private javax.swing.JButton btnRetirarVehiculo;
    private javax.swing.JComboBox<String> cbxTipoArrendamiento;
    private javax.swing.JComboBox<Vehiculo> cbxVehiculo;
    private rojeru_san.componentes.RSDateChooser chooserFechaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtBuscarEspacio;
    private javax.swing.JTextField txtEspacio;
    private javax.swing.JTextField txtFechaIngreso;
    // End of variables declaration//GEN-END:variables
}
