/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorParqueadero;
import ec.ups.edu.controlador.ControladorVehiculo;
import ec.ups.edu.modelo.Parqueadero;
import ec.ups.edu.modelo.Vehiculo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santi
 */
public class VentanaRegistroParqueadero extends javax.swing.JInternalFrame {

    ControladorVehiculo controladorVehiculo;
    ControladorParqueadero controladorParqueadero;
    Vehiculo vehiculo;

    public VentanaRegistroParqueadero() {
        initComponents();

        controladorVehiculo = ControladorVehiculo.getInstancia();
        controladorParqueadero = ControladorParqueadero.getInstancia();
        vehiculo = new Vehiculo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void listarTodo() {

        DefaultTableModel modelo = (DefaultTableModel) tblParqueadero.getModel();
        modelo.setRowCount(0);

        List<Parqueadero> lista = controladorParqueadero.findAll();

        if (lista.isEmpty()) {

            JOptionPane.showMessageDialog(this, "No existen registros");

        } else {

            for (Parqueadero parqueadero : lista) {

                Object[] objeto = {parqueadero.getId(), parqueadero.getIngreso(), parqueadero.getPuesto(), parqueadero.getSalida(),
                    parqueadero.getTipo(), parqueadero.getTotal()};

                modelo.addRow(objeto);

            }

            tblParqueadero.setModel(modelo);

        }

    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblParqueadero = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnListarTodo = new javax.swing.JButton();

        setClosable(true);

        tblParqueadero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ingreso", "Puesto", "Salida", "Tipo", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblParqueadero);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("PARQUEADERO");

        btnListarTodo.setText("Listar todo");
        btnListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarTodo)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarTodo)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodoActionPerformed

        listarTodo();

    }//GEN-LAST:event_btnListarTodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblParqueadero;
    // End of variables declaration//GEN-END:variables
}
